apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mina-common.fullname" . }}
  labels:
    {{- include "mina-common.labels" . | nindent 4 }}
spec:
  backoffLimit: 30
  template:
    metadata:
      labels:
        {{- include "mina-common.labels" . | nindent 8 }}
    spec:
      serviceAccount: {{ default "default" .Values.serviceAccount }}
      restartPolicy: OnFailure
      initContainers:
        - name: wait
          image: alpine/k8s:1.28.0
          command: [ "sh", "/scripts/wait.sh", {{ .Values.nodes | quote }} ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          env:
            - name: INSTANCE
              value: {{ .Release.Name }}
      containers:
        - name: main
          image: alpine/k8s:1.28.0
          command: [ "sh", "/scripts/test.sh", {{ .Values.nodes | quote }} ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          env:
            - name: INSTANCE
              value: {{ .Release.Name }}
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-scripts
