nodes: seed ocaml rust
global:
  readinessProbe: P2PSocket

seed:
  daemonJson:
    local:
      path: /var/lib/coda/berkeley.json
  libp2p:
    secret: seed-libp2p
  isSeed: true

ocaml:
  peers:
    - name: seed
      peerId: 12D3KooWBT8pyJAfWJhdeGYAtKvcaUmm78ExyZ6uo6BEimYNVat1
  daemonJson:
    local:
      path: /var/lib/coda/berkeley.json
  seedWaitTimeout: 5

rust:
  peers:
    - name: seed
      peerId: 12D3KooWBT8pyJAfWJhdeGYAtKvcaUmm78ExyZ6uo6BEimYNVat1
