apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocaml-test-node.fullname" . }}
spec:
  selector:
    {{- include "ocaml-test-node.selectorLabels" . | nindent 4 }}
  ports:
    - name: external
      port: 8302
      targetPort: external
